### ISSUE TITLE
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema

### ISSUE THREAD

**Issue by suneelkumar91** [TheRamey/spin-react#1]
npm install working fine but getting below error once running "npm start" command:
- configuration has an unknown property 'postcss'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           postcss: ...
         }
       })
     ]
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/home/suneel/reactjs_project/SPIN-Dashboard-Package-1.3.3/Full-Version-ReactJS/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/home/suneel/reactjs_project/SPIN-Dashboard-Package-1.3.3/Full-Version-ReactJS/server/main.js:34:20)
    at Module._compile (module.js:624:30)
    at loader (/home/suneel/reactjs_project/SPIN-Dashboard-Package-1.3.3/Full-Version-ReactJS/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/suneel/reactjs_project/SPIN-Dashboard-Package-1.3.3/Full-Version-ReactJS/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/suneel/reactjs_project/SPIN-Dashboard-Package-1.3.3/Full-Version-ReactJS/bin/server.js:2:1)
    at Module._compile (module.js:624:30)
    at loader (/home/suneel/reactjs_project/SPIN-Dashboard-Package-1.3.3/Full-Version-ReactJS/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/suneel/reactjs_project/SPIN-Dashboard-Package-1.3.3/Full-Version-ReactJS/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)

Node version - v8.6.0
npm version - 3.5.2

**Comment by suneelkumar91** [comment]
Fixed by switching the node version '8.5.0'
